/**:
  ros__parameters:
    localization:
      type: diagnostic_aggregator/AnalyzerGroup
      path: localization
      analyzers:
        cartographer:
          type: diagnostic_aggregator/GenericAnalyzer
          path: cartographer
          contains: [": cartographer"]
          timeout: 2.0